name: CI/CD
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23
      - name: Install dependencies
        run: go get -v -t ./...
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
